# Generated by Django 4.1 on 2023-02-03 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 10, 44, 25, 109318)),
        ),
    ]
