# Generated by Django 4.1 on 2023-02-08 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_options_alter_auction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='bid',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 15, 42, 50, 785035)),
        ),
    ]
