# Generated by Django 4.1 on 2023-02-08 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auction_date_alter_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 8, 15, 44, 22, 229151)),
        ),
    ]
