# Generated by Django 4.1 on 2023-02-09 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_auction_bid_bid_auction_alter_auction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='initial_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 9, 53, 50, 6399)),
        ),
    ]
