# Generated by Django 4.1 on 2023-04-03 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_bid_bidder_alter_auction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='offert',
            new_name='offer',
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 11, 26, 7, 577950)),
        ),
    ]
